project:
  type: website

website:
  title: "LMS Undergraduate Summer School 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - speakers.qmd
      - text: Programme
	menu: 
	  - text: Programme - overview
	    href: programme.qmd
	  - text: Programme with abstracts
	    href: abstracts.qmd
      - registration.qmd
      - text: Local information
        menu:
          - text: Accommodation
            href: local.qmd#accommodation
          - text: Catering
            href: local.qmd#catering
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



