project:
  type: website

website:
  title: "LMS Undergraduate Summer School 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - speakers.qmd
      - text: Programme
        menu:
          - text: Programme - overview
            href: programme.qmd
          - text: Programme with abstracts
            href: abstracts.qmd
      - courses.qmd
      - registration.qmd
      - text: Local information
        menu:
          - text: Accommodation
            href: local.qmd#accommodation
          - text: Directions
            href: local.qmd#directions
          - text: Catering
            href: local.qmd#catering
          - text: Sports facilities
            href: local.qmd#sports-facilities
          - text: Things to do in Bath
            href: local.qmd#things-to-do-in-bath
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



