---
title: "About"
---

The summer school is organised by the [Department of Mathematical Sciences](https://www.bath.ac.uk/departments/department-of-mathematical-sciences/) at the University of Bath, with generous support from the [London Mathematical Society](https://www.lms.ac.uk/) and the Liber Stiftung ([Liber Foundation](https://www.fundraiso.ch/sponsor/fondation-liber/)).

The Department of Mathematical Sciences has over 70 academic staff from all areas of Mathematics. 
The Department research divides itself into six major groupings (Algebra and Geometry,
Analysis, Applied and Interdisciplinary Mathematics, Numerical Analysis and Data Science, Probability, and Statistics).  The Department is also home to the EPSRC Centre for Doctoral Training SAMBa (Statistical Applied Mathematics at Bath) and the Institute for Mathematical Innovation. 
Our department currently holds an Athena SWAN Gold Award. 

Contact the organisers by emailing: [lms-summer-school `at' bath.ac.uk](mailto:lms-summer-school@bath.ac.uk)
