---
title: "Programme with abstracts"
format: html
tbl-colwidths: [20,80]
---



All classes and talks take place in the Wolfson lecture room (4W 1.7) on the lower ground floor of building 4 West, except for some computer labs.
See the [Campus map here](local.qmd#directions).
See also the [Programme overview](programme.qmd).


## Week 1

| Sunday | 13 July | 
| :-- | ----- |
| From 15.00 | Check-in (East accommodation centre)|
| 15:45-16:00 | Zoom test |
| 16:15 | Tea (4W Atrium) |
| 16:45 | Quiz (4W 1.7)
| 19:15 - 20:00 | Dinner (Lime tree) | 


| Monday | 14 July |
| -- | ----- |
| 9:30 - 12:00 | Keating: Knot theory, knot practice | 
| | Abstract: Knot theory is a vibrant area of modern mathematics; it has a rich history, and far-fetching connections, many of them to other areas of science. This mini-course will provide an introduction to the subject from a mathematician's perspective. We will start with some basic definitions and properties. We will then explore, first, some links with low-dimensional topology; and second, connections with algebra. We will emphasise examples throughout. |
| 12:00 - 13:30 | Lunch (atrium) |
| 13:30 - 16:00 | Keating (continued) |
| 16:15 - 17:15 | Lawson: Information in large data: Lessons from population genomics on relating mathematical models to algorithmic scaling|
| | Abstract: One of the key challenges in applying mathematics is to figure out what the question should be. This talk distils population genetics into mathematical statements of how to represent data. We will see how answering questions directly - how to store a matrix - lead to good, but incomplete answers. We will see how understanding the mathematical generative process leads to drastically better algorithms for storage and analysis, exploiting sparsity with the "positional Burrows-Wheeler Transform". The takehome message - of choosing data representations based on mathematical understanding rather than brute-force - points towards improvements in many disciplines, including the AI analysis of free text.| 
| 19:15 - 20:00 | Dinner (Lime tree) |


| Tuesday | 15 July |
| - | ----- |
| 9:30 - 12:00 | Keating (continued) |
| 12:00 - 13:30 | Lunch (outlets*) |
| 13:30 - 16:00 | Touloupou: Statistical inference for epidemic models |
| | Abstract: This mini-course introduces the mathematical and statistical foundations of epidemic modeling, focusing on stochastic discrete-time models such as the SIS and the SIR frameworks. Students will learn how to represent disease spread using compartmental models, simulate epidemic dynamics using probabilistic transitions, and estimate key parameters like transmission and recovery rates from complete data. The course covers both likelihood-based and Bayesian inference methods, with hands-on implementation in R. By the end, students will be equipped to build, simulate, and fit simple epidemic models and understand their role in real-world public health analysis. |
| 16:15 - 17:15 | Green: Fourier analysis in additive number theory, and its generalisations | 
| | Abstract: Fourier analysis arose historically from questions in applied mathematics, but it has also been very successful at studying pure mathematical problems, for instance to do with representing numbers as sums of squares or sums of primes. I will discuss this a little bit, and then move on to give a hint of more recent developments in which Fourier analysis has been generalised in order to attack problems that the classical theory was unable to handle. |
| 17.30-19.45 | Outdoor games (Medical centre sports field) <br>&nbsp;<br>Rain stopped play |
| 19.15-20.00 | Dinner (Lime tree) |



| Wednesday | 16 July | 
| - | ----- |
| 9:30 - 12:00 | Touloupou (continued) |
| 12:00 - 13:30 | Lunch (outlets*) |
| 13:30 - 15:45 | Touloupou (continued) |
| | Computer lab (CB 5.13), using [R](R.qmd) |
| 16:15 - 17:15 | Phil Trinh: The next step: PhDs and/or industry |
| | In this talk, I will describe the UK PhD landscape and pursuing a mathematics PhD. I’ll describe the interview process for a typical PhD studentship and the decision-making process. I’ll give some tips and tricks on the application process. Finally, I’ll discuss the interesting careers you can pursue, with and without a PhD, outside of academia. |
| 18:00-21:00 | Pizza and board games (Claverton rooms, upstairs in 2W) |

| Thursday | 17 July | 
| - | ----- |
| 9:30 - 12:00 | Sousi: Random walks, electrical networks and uniform spanning trees | 
| | Abstract: A random walk is called recurrent if it returns to its starting point infinitely many times with probability one. Otherwise it is called transient. How do we determine whether a walk is transient or recurrent? One way is by viewing the graph as an electrical network and calculating effective resistances. This course will start by developing the theory of electrical networks and the connection to random walks. Kirchhoff in 1847 was the first one to find a connection of spanning trees to electrical networks. Spanning trees in a connected graph are basic objects of great interest in combinatorics and computer science. In this course we will study what a typical spanning tree looks like and we will discuss elegant sampling algorithms using random walks due to Aldous, Broder and Wilson from the 1990's. These connections have yielded many insights on the geometry of uniform spanning trees; this is a topic of intense current research. |
| 12:00 - 13:30 | Lunch (outlets*) |
| 13:30 - 16:00 | Sousi (continued) |
| 16:15 - 17:15 | Tripaldi: SubRiemannian geometry in real life: how to parallel park your car |
| | Abstract: A nonholonomic system is a type of mechanical system that cannot move in an arbitrary direction, and is instead constrained by its physical structure and the environment. Examples of such systems include cars, rockets, and wheeled mobile robots. <br>&nbsp; <br> In this talk, we'll explore how the constraints of nonholonomic motion shape control strategies, using the parallel parking problem as a guiding example. Along the way, we’ll see how subRiemannian geometry encodes feasible trajectories and how tools from control theory and differential geometry help us navigate this constrained world. |
| 19:15 - 20:00 | Dinner (Lime tree) |

| Friday | 18 July |
| - | ----- |
| 9:30 - 12:00 | Sousi (continued) |
| 12:00 - 13:30 | Lunch (outlets*)
| 14:15 - 16:15 | Walking tour of Bath |
| | Departing at 14:15 from Abbey Churchyard (outside the Roman Baths and Pump Room, in front of the City of Bath’s Mayor’s Honorary Guides noticeboard).
| 16:30 - 18:00 | Roman Baths |
| | If you have paid for a ticket, then gather from 16:15 at the main entrance from the Abbey Churchyard. The group will need to be ready to enter no later than 16:30.|

| Saturday | 19 July |
| - | ----- |
| 10.30 | Coach departing to Avebury (from [coach zone in centre of East car park](https://www.bath.ac.uk/corporate-information/visitor-car-parking-on-our-claverton-down-campus/#coach-drop-off-zone-b0dc)) |
| | Gather at East car park around 10:15 for excursion Avebury. We'll bring a packed lunch. We have a guided tour 12.30-13.30. The rest of the time you can explore the stone circle, manor gardens and museum.|
| 15.00 | Coach departing from Avebury |

| Sunday | 20 July |
| -- | ----- |
| 10:00 - 11:45 | Skyline walk |
| | Group walk along a portion of the Bath skyline walk, leaving at 10am from the Lime Tree, arriving to Prior Park around 11am  | 
| 11:45 | Entry to Prior Park |
| | To enter Prior Park with the group (as opposed to buying a ticket yourself) either come along on the preceding walk or meet at the main entrance to Prior Park (from Ralph Allen Drive) at 11am. You can then stay as long as you like. There is a cafe offering sandwiches and cakes (but no hot food), or you can bring something for a picnic. |


## Week 2

| Monday | 21 July |
| -- | ----- |
| 9:30 - 12:00 | Speight: Topological solitons | 
| | Abstract: Topological solitons are smooth, spatially localized solutions of nonlinear field theories, which owe their existence and stability to topological considerations: they cannot be removed or destroyed by any continuous deformation of the system's fields (for example, time evolution). They occur across many branches of physics, most notably condensed matter physics, where they model, inter alia, magnetic flux tubes in superconductors and magnetization bubbles in ferromagnets. <br>&nbsp; <br>An intriguing possibility is that they might actually represent elementary particles (protons, neutrons, electrons, or something more exotic - and so far unobserved - such as magnetic monopoles). They sit very naturally within Einstein's theory of Special Relativity and already (before "quantization") exhibit many fundamentally particle-like properties (conserved topological "quantum numbers", and antimatter counterparts, for example). If such fundamental solitons do exist, they would account elegantly for some otherwise mysterious facts about the universe. Perhaps more important for mathematicians, their study involves a fascinating mixture of differential geometry, mathematical analysis and computer simulations. <br>&nbsp;<br>This minicourse will introduce a selection of the most important ideas underlying the study of topological solitons by focussing on simple examples in one and two spatial dimensions. I will assume familiarity with linear algebra, multivariable calculus, including vector calculus (div, grad, curl, Stokes's Theorem etc), complex analysis and some basic notions from Newtonian mechanics (kinetic energy, potential energy, force etc). No background in topology or advanced differential geometry will be assumed. | 
| 12:00 - 13:30 |  Lunch (outlets*) | 
| 13:30 - 16:00 | Speight (continued) |
| 16:15 - 17:15 | Horton: Neutron transport from a probabilistic perspective | 
| | Abstract: Neutron transport describes the dynamics of neutrons undergoing fission in environments such as nuclear reactors. Understanding the growth rate of the number of neutrons in the reactor and their long-term spatial distribution is crucial for reactor design and safety. In this talk, we will discuss how to model neutron transport via a branching process and how this can be helpful to understand such properties.  |
| 19:15 - 20:00 | Dinner (Lime tree) |

| Tuesday | 22 July |
| -- | ----- |
| 9:30 - 12:00 | Speight (continued) | 
| 12:00 - 13:30 | Lunch (4W&nbsp;Atrium) |
| 13:30 - 16:00 | Luckins: Free boundary problems in phase-change and porous media | 
| | Abstract: Many examples of partial-differential-equation (PDE) models that you will have encountered in your degree so far are posed on prescribed domains. A free-boundary problem is a PDE model posed on a domain where at least part of the boundary moves, and where the position and speed of the moving boundary must be determined as part of the model solution. Free-boundary problems are more complicated to solve and analyse mathematically due to their inherent nonlinearity, and are particularly tricky in scenarios where the free-boundary becomes unstable, but they are crucial to understand as they appear in many important real-world problems. In this minicourse, we will explore two classical examples of free-boundary problems: (i) melting/freezing problems and (ii) fluid flows in porous media, and discuss their modern applications in modelling sea ice, heat batteries, metallurgy, and carbon sequestration. |
| 16:15 - 17:15 | Spence: Numerical analysis of wave scattering problems |
| | Abstract: Solving high-frequency wave-scattering problems in an accurate, efficient, and reliable way is a longstanding open problem in numerical analysis. Perhaps surprisingly, the numerical analysis of high-frequency wave problems has traditionally not taken advantage of the tools and techniques from the PDE theory of high-frequency waves. This talk will give an example of how these PDE tools and techniques can be used in a striking way in the numerical analysis of high-frequency waves. |
| 19:15 - 20:00 | Dinner (Lime tree) |

| Wednesday | 23 July |
| -- | ----- |
| 9:30 - 12:00 | Luckins (continued) | 
| 12:00 - 13:30 | Lunch (outlets*) |
| 16:15 - 17:15 | PhD student talks |
| 19:15 - 20:00 | Dinner (Lime tree) |
| 20:15 - 21:15| N is a number (8W 1.1) |
| | Documentary about Paul Erd&odblac;s. James Davenport can answer questions about "Uncle Paul".|

| Thursday | 24 July |
| -- | ----- |
| 9:30 - 12:00 | Shelton: Resummation of divergent series expansions and the Stokes phenomenon |
| | Abstract: Asymptotic methods are widely used across mathematics, physics, and engineering to find solutions to differential equations that lack exact closed-form solutions. In these, approximate solutions are sought under the limit as certain parameters of the system become small (or large). Well-known examples are the limit of vanishing viscosity in fluid dynamics (large Reynolds number) under which boundary layers and hydrodynamic instabilities emerge, and the limit of small Planck constant in theoretical physics. A distinguishing feature of these expansions is that they typically diverge. Divergent expansions may at first seem unusual in comparison to convergent series, which most undergraduate students are well accustomed with. However, in practice, divergent expansions can significantly outperform their convergent counterparts; often, only a few terms from a divergent expansion are needed to outperform thousands from a convergent expansion. Thus, their study continues to be an active area of research in mathematics.<br>&nbsp;<br>In this course, we will resolve many of the issues that arise with divergent series expansions (mainly the Stokes phenomenon), both by series resummation and optimal truncation of the full asymptotic transseries. The techniques developed will first be applied to the example studied by G.G. Stokes in his pioneering work: Airy's equation, which is a linear differential equation. We will then proceed to find asymptotic solutions to a nonlinear example from fluid dynamics, the fifth-order KdV equation. |
| 12:00 - 13:30 | Lunch (outlets*) |
| 13:30 - 16:00 | Shelton (continued) |
| 16:15 - 17:15 | Leary: Decision problems in topology |
| | Abstract: A decision problem asks whether there can be an algorithm for deciding the answer to some family of yes/no questions.  Topology is the branch of topology in which you ignore distance and you are allowed to distort or stretch things without breaking them. I'll describe some questions in topology where there is an algorithm to answer them, some where there cannot be any algorithm, and some where we simply do not know.|
| 18:30 | Dinner (Pearl of India) |
| |  Dinner at [Pearl of India restaurant](https://pearlofindia.co.uk/), [8A Quiet Street, BA1 2JS](https://www.google.com/maps/place/Pearl+of+India/@51.3788119,-2.3533281,15z/data=!4m6!3m5!1s0x487181138406a74f:0x944539fd8608ef99!8m2!3d51.3832563!4d-2.3616022!16s%2Fg%2F1vfp3263?entry=ttu&g_ep=EgoyMDI1MDcxNi4wIKXMDSoASAFQAw%3D%3D) (40 minute walk from campus, or take U1 bus to North Parade and walk from there) |

| Friday | 25 July |
| -- | ----- |
| 9:30 - 12:00 | Shelton  (continued) |
| 12:00 - 13:30 | Lunch (outlets*) |


* Use vouchers in any outlet on campus
