---
title: "Course materials"
format: html
tbl-colwidths: [20,80]
---



## Week 1

### Keating: Knot theory, knot practice

**Abstract:** Knot theory is a vibrant area of modern mathematics; it has a rich history, and far-fetching connections, many of them to other areas of science. This mini-course will provide an introduction to the subject from a mathematician's perspective. We will start with some basic definitions and properties. We will then explore, first, some links with low-dimensional topology; and second, connections with algebra. We will emphasise examples throughout.

**Materials**

* [Problem Sheet 1 (updated version)](course_materials/KTKP%20ES1v2.pdf)
* [Problem Sheet 2 (updated version) ](course_materials/KTKP%20ES2v2.pdf)


### Touloupou: Statistical inference for epidemic models 

**Abstract:** This mini-course introduces the mathematical and statistical foundations of epidemic modeling, focusing on stochastic discrete-time models such as the SIS and the SIR frameworks. Students will learn how to represent disease spread using compartmental models, simulate epidemic dynamics using probabilistic transitions, and estimate key parameters like transmission and recovery rates from complete data. The course covers both likelihood-based and Bayesian inference methods, with hands-on implementation in R. By the end, students will be equipped to build, simulate, and fit simple epidemic models and understand their role in real-world public health analysis. 

**Materials**

* [Lecture slides](course_materials/Notes_EpidemicModels.pdf)
* [Tutorial instructions](course_materials/Tutorial_SIS.pdf)
* [R code for tutorial](course_materials/Tutorial_SIScode.R)

### Sousi: Random walks, electrical networks and uniform spanning trees 


**Abstract:** A random walk is called recurrent if it returns to its starting point infinitely many times with probability one. Otherwise it is called transient. How do we determine whether a walk is transient or recurrent? One way is by viewing the graph as an electrical network and calculating effective resistances. This course will start by developing the theory of electrical networks and the connection to random walks. Kirchhoff in 1847 was the first one to find a connection of spanning trees to electrical networks. Spanning trees in a connected graph are basic objects of great interest in combinatorics and computer science. In this course we will study what a typical spanning tree looks like and we will discuss elegant sampling algorithms using random walks due to Aldous, Broder and Wilson from the 1990's. These connections have yielded many insights on the geometry of uniform spanning trees; this is a topic of intense current research. 

## Week 2

### Speight: Topological solitons 

**Abstract:** Topological solitons are smooth, spatially localized solutions of nonlinear field theories, which owe their existence and stability to topological considerations: they cannot be removed or destroyed by any continuous deformation of the system's fields (for example, time evolution). They occur across many branches of physics, most notably condensed matter physics, where they model, inter alia, magnetic flux tubes in superconductors and magnetization bubbles in ferromagnets. <br>&nbsp; <br>An intriguing possibility is that they might actually represent elementary particles (protons, neutrons, electrons, or something more exotic - and so far unobserved - such as magnetic monopoles). They sit very naturally within Einstein's theory of Special Relativity and already (before "quantization") exhibit many fundamentally particle-like properties (conserved topological "quantum numbers", and antimatter counterparts, for example). If such fundamental solitons do exist, they would account elegantly for some otherwise mysterious facts about the universe. Perhaps more important for mathematicians, their study involves a fascinating mixture of differential geometry, mathematical analysis and computer simulations. <br>&nbsp;<br>This minicourse will introduce a selection of the most important ideas underlying the study of topological solitons by focussing on simple examples in one and two spatial dimensions. I will assume familiarity with linear algebra, multivariable calculus, including vector calculus (div, grad, curl, Stokes's Theorem etc), complex analysis and some basic notions from Newtonian mechanics (kinetic energy, potential energy, force etc). No background in topology or advanced differential geometry will be assumed.

**Materials**

* [Handout](course_materials/solitons.pdf) with course outline and exercises

### Luckins: Free boundary problems in phase-change and porous media 

**Abstract:** Many examples of partial-differential-equation (PDE) models that you will have encountered in your degree so far are posed on prescribed domains. A free-boundary problem is a PDE model posed on a domain where at least part of the boundary moves, and where the position and speed of the moving boundary must be determined as part of the model solution. Free-boundary problems are more complicated to solve and analyse mathematically due to their inherent nonlinearity, and are particularly tricky in scenarios where the free-boundary becomes unstable, but they are crucial to understand as they appear in many important real-world problems. In this minicourse, we will explore two classical examples of free-boundary problems: (i) melting/freezing problems and (ii) fluid flows in porous media, and discuss their modern applications in modelling sea ice, heat batteries, metallurgy, and carbon sequestration.


## Shelton: Resummation of divergent series expansions and the Stokes phenomenon 

**Abstract:** Asymptotic methods are widely used across mathematics, physics, and engineering to find solutions to differential equations that lack exact closed-form solutions. In these, approximate solutions are sought under the limit as certain parameters of the system become small (or large). Well-known examples are the limit of vanishing viscosity in fluid dynamics (large Reynolds number) under which boundary layers and hydrodynamic instabilities emerge, and the limit of small Planck constant in theoretical physics. A distinguishing feature of these expansions is that they typically diverge. Divergent expansions may at first seem unusual in comparison to convergent series, which most undergraduate students are well accustomed with. However, in practice, divergent expansions can significantly outperform their convergent counterparts; often, only a few terms from a divergent expansion are needed to outperform thousands from a convergent expansion. Thus, their study continues to be an active area of research in mathematics.<br>&nbsp;<br>In this course, we will resolve many of the issues that arise with divergent series expansions (mainly the Stokes phenomenon), both by series resummation and optimal truncation of the full asymptotic transseries. The techniques developed will first be applied to the example studied by G.G. Stokes in his pioneering work: Airy's equation, which is a linear differential equation. We will then proceed to find asymptotic solutions to a nonlinear example from fluid dynamics, the fifth-order KdV equation.

