---
title: "Welcome"

---

The LMS Undergraduate Summer School will take place at the University of Bath, **14 - 25 July 2025**. 


The LMS Undergraduate Summer Schools is a two-week course, which is held every summer at a UK university. The aim is to introduce modern mathematics to the best UK undergraduates who will enter their final year the following autumn, and encourage them to think about an academic career in maths. The LMS Undergraduate Summer School consists of a combination of short lecture courses with problem-solving sessions and colloquium-style talks from leading mathematicians. 50 places are available to students per year.

For more information about the history of LMS Summer Schools please visit the [London Mathematical Society Summer School](https://www.lms.ac.uk/events/lms-summer-schools) webpage.

For information on how to participate, see the [registration page](registration.qmd). The deadline for nominations is 
**30 April 2025**. 

## Speakers

This is a preliminary list of speakers and will still be updated.

| Minicourse  Lecturers	| Colloquium Speakers |
|----|----|
| Ian Griffiths (Oxford)  |	Ben Green (Oxford)|
| Ailsa Keating (Cambridge)	| Emma Horton (Warwick)| 
| Josh Shelton (St Andrews) |Dan Lawson (Bristol)|
| Martin Speight (Leeds)|  Ian Leary (Southampton)|
| Perla Sousi (Cambridge)| Euan Spence (Bath)	|
| Panayiota Touloupou (Birmingham) |	Francesca Tripaldi (Leeds)|


## Local organisers

* Johannes Nordstrom (Lead) 
* James Davenport
* Vangelis Evangelou
* Marcel Ortgiese
* Phil Trinh

Contact the organisers by emailing [lms-summer-school *at* bath.ac.uk](mailto:lms-summer-school@bath.ac.uk).

<!-- |Organising committee|
|---|
|Johannes Nordstrom (Lead)|
|James Davenport|
|Vangelis Evangelou|
|Marcel Ortgiese|
|Phil Trinh|-->

## Funding bodies and sponsorship

The Summer School is generously supported by the [London Mathematical Society](https://www.lms.ac.uk/) and the Liber Stiftung ([Liber Foundation](https://www.fundraiso.ch/sponsor/fondation-liber/)).