---
title: "Local information"
---

## Accommodation

Students will be provided with single en-suite accommodation on campus from Sunday 13 July (check-in from 3pm) until Friday 25 July.
<!--Each room will be en suite with access to a shared kitchen and communal space. All bed linen will be provided and washed weekly.-->


## Directions

[Campus map](https://www.bath.ac.uk/publications/claverton-down-campus-map/attachments/university-campus-map.pdf)

Bus U1 goes from the train station to the campus. The main bus stop (arrivals square) is close to the accommodation.

It is about a [40 minute walk](https://www.google.com/maps/dir/51.377389,-2.3566945/51.3791194,-2.3287683/@51.3779515,-2.3379405,17z/data=!4m2!4m1!3e2?entry=ttu&g_ep=EgoyMDI1MDYxNy4wIKXMDSoASAFQAw%3D%3D) from the station to campus (steep uphill in parts). The most convenient pedestrian entrance to the campus (reasonably close to the 4 West building, where the classes and talks take place) is at the intersection by the building labelled "The Woodlands" on the campus map.


## Meals


All meals (breakfast, lunch and dinner) will be provided, starting with dinner on Sunday 13 July and ending with lunch on Friday 25 July, except for some meals at the weekend.

### Breakfast

Served daily 7.30-9.00 at the Lime Tree.

#### Lunch

* 14, 22 July: Buffet in 4W Atrium
* 15-18, 21, 23-35 July: You will be issued with vouchers that you can use in a variety of outlets on campus. 
   * The Lime Tree: Hot dishes, pizzas, pasta and dalad bar/deli. Can get very busy.
   * The Pavillion (in 10E lower ground floor): Some hot dishes and ciabattas
   * The SPorts cafe (int he SPorts Training Village): Hot dishes similar to those at Lime Tree, but portion sizes suspected to be larger to cater for athletes
   * 4W cafe (in level 2 4W): Some hot dishes, sandwiches and salads
   * The Market: shop at the Student Union that has some groceries
* 19 July: We will bring a packed lucnh on the excursion to Avebury

#### Dinner

* 13-15, 17, 21-23 July: We have a separate counter service at the Lime Tree with a few different meal options (no need to use vouchers)
* 16 July: Pizza and boardgames in the Claerton rooms (level 3 in 2E)
* 24 July: Conference dinner

For dinner on 18-19 July and lunch on 20 July we have not organised any group meals, as we expect that many of you will make your own programmes at the weekend. If you are staying around on campus, then you can use vouchers at the Lime Tree.

The campus includes a Fresh shop that provides additional food and essentials (but the lunch vouchers are not valid there).


## Things to do in Bath

You might consider the following activities in Bath in your spare time: 

* [Herschel museum of astronomy](https://herschelmuseum.org.uk/), situated in the house from where Uranus was discovered (£11 entry with NUS card)
* Hire a bike (for example [Bath Bike hire](https://www.bathebikehire.co.uk/) or [Julian House](https://jhbikeworkshop.org/bath-city-centre-e-bike-hire/)) and follow for example: 
    * The two tunnels cycle route (see eg [here](https://www.bathebikehire.co.uk/two-tunnels-cycle-route/))
    * Cycle to Bristol on the [Bristol-Bath railway path](https://www.sustrans.org.uk/find-a-route-on-the-national-cycle-network/bristol-and-bath-railway-path/).
* [Holbourne museum](https://holburne.org/) (£7 entry with NUS card)
* [American museum](https://www.americanmuseum.org/), 15 minute walk from the campus (£13.50 for students)
* [Jane Austen centre](https://janeausten.co.uk/), currently celebrating the 250th anniversary of Jane AUsten's birth
* [No 1 Royal Crescent museum](https://no1royalcrescent.org.uk/)
* [Prior Park landscape garden](https://www.nationaltrust.org.uk/visit/bath-bristol/prior-park-landscape-garden) (£10 entry, or free if you come for the group visit at 11am on Sunday 20 July)
* Bath University has excellent sports facilities, which are available to you on a [pay-as-you-go basis](https://www.teambath.com/about/prices-bookings/pay-and-play-rates/). (Concession rates require an NUS card.)

