---
title: "Programme"
---


The exact timings will be confirmed nearer the time.

## Week 1


|Date | Morning | Afternoon |
|---|---|---|
|Sunday, 13 July | |  Arrival. Dinner will be provided |
|Monday, 14 July| Ailsa Keating, Minicourse part 1 | Ailsa Keating, minicourse part 2|
| |  | Dan Lawson, colloquium |
|Tuesday, 15 July | Ailsa Keating, Minicourse part 1 | Panayiota Touloupou, minicourse part 1|
| | | Ben Green, colloquium |
|Wednesday, 16 July | Panayiota Touloupou, minicourse part 2 | Panayiota Touloupou, minicourse part 3 |
| | | Talk tbc|
|Thursday, 17 July | Perla Sousi, minicourse part 1| Perla Sousi, minicourse part 2 |
| | | Franscesca Tripaldi, colloquium | 
| Friday, 18 July | Perla Sousi, minicourse part 3 | Exploring Bath |
| Saturday, 19 July | Excursion | Excursion |
| Sunday, 20 July | Free time | Free time |



## Week 2

|Date | Morning | Afternoon |
|---|---|---|
|Monday, 21 July| Martin Speight, minicourse part 1 | Martin Speight, minicourse part 2 |
| | | Emma Horton, colloquium |
|Tuesday, 22 July | Martin Speight, minicourse part 3 | Ian Griffiths, minicourse part 1	|
| |  | Euan Spence, colloquium |
|Wednesday, 23 July |Ian Griffiths, minicourse part 2 | Ian Griffiths, minicourse part 3 |
| | | Talk tbc |
| Thursday, 24 July | Joshua Shelton, minicourse part 1 | Joshua Shelton, mincourse part 2 |
| | |Ian Leary, colloquium |
| Friday, 25 July | Joshua Shelton, minicourse part 3 | Departure after lunch |






