---
title: "Registration"
---

## How to participate

<!-- Participants will be students on UK mathematics programmes who are entering their final year of study in autumn 2025. Students will be nominate by their home department via their nominated representative member of staff. -->


Each University (mathematics and/or statistics department) in the UK via their nominated representative member of staff can select up to three students to participate in this summer school. 
Each candidates must have completed (the equivalent of) at least two full academic years of an undergraduate degree in mathematics/statistics at the time that the Summer School takes place and be continuing their mathematics undergraduate degree after the Summer School has finished. The final attendees will be decided by the local Organising Committee at the University of Bath. 

Students who would like to participate are recommended to discuss the event with their Head of Department, please do not contact the organising committee directly.

## Registration form

If you would like to participate, please discuss with your Head of Department, and then complete and return this [nomination form (.docx)](Summer School Nomination Form 2025.docx), together with a copy of your academic transcript to date, to your Head of Department or LMS Representative who will forward nominations to the University of Essex (jbailef@essex.ac.uk).

Nominations should be received by **30 April 2025**  and be sent to [lms-summer-school@bath.ac.uk](mailto:lms-summer-school@bath.ac.uk). Institutions are asked to send their nominations with a cover letter that ranks their nominees and to send nominations and transcripts in either Word or .PDF format.

## Registration fee 


The LMS asks that for each candidate accepted onto the LMS Undergraduate Summer School their home Department provides a £250 contribution. 


## Criteria for Nominations

To achieve an inclusive and cooperative working atmosphere, each LMS Undergraduate Summer School is usually limited to 50 in-person participants, so the organisers will need to be highly selective.  Indeed a high level of ability and enthusiasm for mathematics is essential to enjoy and benefit from the LMS Undergraduate Summer School.
 
Participation of women students in the LMS Undergraduate Summer School is particularly important as there is a recognised lack of women continuing on to postgraduate study.  To this end UK Institutions are asked to nominate both female and male students. 